version: "3.7"

services:
  postgres:
    image: postgres:16-alpine3.19
    volumes:
      - ./database:/var/lib/postgresql/data/
    ports:
      - "172.17.0.1:5432:5432"
    restart: always
    env_file:
      - .env

  backend:
    build:
      context: .
    restart: always
    command: ["backend/docker/app.sh"]
    ports:
      - "172.17.0.1:4000:4000"
    volumes:
      - .:/backend
    depends_on:
      - postgres

  admin:
    image: adminer
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres

